### PR TITLE
Update bullet

### PR DESCRIPTION
**Pull request by Brouilles**
Fix bug with last version of Clang (Xcode).

### CODE REVIEW

**Comment by Brouilles** [comment]
Fix this Xcode / Clang error: https://github.com/bulletphysics/bullet3/issues/2418

**Comment by GregSlazinski** [comment]
Hi and thanks for you contribution(s).

Since every change has to be verified by me for quality and safety purposes, I can't merge it, because the commit is simply too big for me to check.

Updating Bullet will require a lot of time, since it requires doing a lot of things.
I'll be able to do it in the future.

But I assume the xcode/clang error is just a warning and not and error?

**Comment by Brouilles** [comment]
It's an error. That prevents compiling on the latest version of Xcode.

**Comment by GregSlazinski** [comment]
will be available in next release

**Pull request closed without merging**
